### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by yconselvan** [jyhmiinlin/pynufft#21]
Trying to install inside docker container

Getting Error: 

```
...
running build_py
error: can't copy './src': doesn't exist or not a regular file

```

Full output of install

```

root@f9f9d415f1e0:/pynufft# python3 setup.py install --user
/usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '2019.2.1rc' to '2019.2.1rc0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing top-level names to pynufft.egg-info/top_level.txt
writing requirements to pynufft.egg-info/requires.txt
writing dependency_links to pynufft.egg-info/dependency_links.txt
writing pynufft.egg-info/PKG-INFO
reading manifest file 'pynufft.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pynufft.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
error: can't copy './src': doesn't exist or not a regular file

```

Dockerfile

```

FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y \
    python3 python3-numpy python3-nose python3-pandas python-h5py \
    python python-numpy python-nose python-pandas python3-h5py \
    pep8 python-pip python3-pip python-wheel \
    python-sphinx && \
    pip install --upgrade setuptools

RUN apt-get update && \
    apt-get install -y \
    x11-xserver-utils

```

**Comment by jyhmiinlin** [comment]
Thank you for reporting this. It seems Docker cannot find src folder. 

I am closing it for now because it is specific to Docker.

**Comment by SadeghMSalehi** [comment]
I'm getting the same error while pip installing in `pyenv`.

**Comment by jyhmiinlin** [comment]
Reopen it. May try to sort it out.

**Comment by jyhmiinlin** [comment]
My pyenv can install pynufft. Close this issue because I cannot replicate the error. 

If you have this trouble again please open a new issue about pyenv. Someone may be able to replicate the issue and help you. 

user@localhost ~ $ which python
/home/user/.pyenv/shims/python
user@localhost ~ $ pyenv virtualenv 3.6.5 foo
Requirement already satisfied: setuptools in /home/user/.pyenv/versions/3.6.5/envs/foo/lib/python3.6/site-packages
Requirement already satisfied: pip in /home/user/.pyenv/versions/3.6.5/envs/foo/lib/python3.6/site-packages
user@localhost ~ $ pyenv local foo
user@localhost ~ $ which python
/home/user/.pyenv/shims/python
user@localhost ~ $ which pip
/home/user/.pyenv/shims/pip
user@localhost ~ $ pip install pynufft
Collecting pynufft
  Cache entry deserialization failed, entry ignored
Collecting numpy (from pynufft)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/75/92/57179ed45307ec6179e344231c47da7f3f3da9e2eee5c8ab506bd279ce4e/numpy-1.17.1-cp36-cp36m-manylinux1_x86_64.whl (20.4MB)
    100% |████████████████████████████████| 20.4MB 95kB/s 
Collecting scipy (from pynufft)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/29/50/a552a5aff252ae915f522e44642bb49a7b7b31677f9580cfd11bcc869976/scipy-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (25.2MB)
    100% |████████████████████████████████| 25.2MB 71kB/s 
Installing collected packages: numpy, scipy, pynufft
Successfully installed numpy-1.17.1 pynufft-2019.2.0 scipy-1.3.1
You are using pip version 9.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
